### PR TITLE
Added OscolaMailboxApi.ino

### PR DESCRIPTION
**Pull request by tamberg**
An alternative to using MQTT, based on the built-in Arduino Yun Mailbox REST API. Should work with all OSCOLA models (just adapt the number of pixels). On the client side, use any browser or Curl to send a GET request to http://arduino.local/rrggbb or http://OSCOLA_LOCAL_IP/rrggbb

### CODE REVIEW

**Comment by lorenzoromagnoli** [comment]
Ciao Thomas, 
I'm trying to collect all the files produced during the ws in a way that is easier for us to document. 
Could you please create a new folder inside ws projects, give it the name of your lamp/project and upload there your code and your design?

Thanks a lot

**Comment by tamberg** [comment]
Sure, will do. Thanks.

**Comment by tamberg** [comment]
Done.

**Comment by lorenzoromagnoli** [comment]
Awesome! 
thanks!

**Pull request merged**
